name: Build
on:
  push:
jobs:
  build-project:
    name: Build miki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install boost
          uses: MarkusJx/install-boost@v2.4.4
          id: install-boost
          with:
            # REQUIRED: Specify the required boost version
            # A list of supported versions can be found here:
            # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
            boost_version: 1.73.0
            # OPTIONAL: Specify a platform version
            platform_version: 18.04
            # OPTIONAL: Specify a custom install location
            boost_install_dir: /home/runner/boost
            # OPTIONAL: Specify a toolset
            toolset: gcc
            # OPTIONAL: Specify an architecture
            arch: x86

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: Build Project
        runs: cmake --build build

      - name: Test Project
        runs: ctest --test-dir build
